### PR TITLE
add firebase to index.html

### PR DESCRIPTION
**Pull request by thecoder876**
i am adding firebase to 1auth
cc @wgyt
**THIS IS A DRAFT, PLS NO MERGE UNTIL I MARK IT AS READY**

### CODE REVIEW

**Comment by GrahamSH-LLK** [comment]
Whatnofirebasedefeatsthepointof1authexistingyouidiot

**Comment by thecoder876** [comment]
> Whatnofirebasedefeatsthepointof1authexistingyouidiot

@GrahamSH-LLK it doesn't we can use it for cloud messaging (aka in-app announcements)

**Comment by GrahamSH-LLK** [comment]
What? Why would an auth app have in-app announcements?!

**Comment by thecoder876** [comment]
> What? Why would an auth app have in-app announcements?!

@GrahamSH-LLK fine i'll do this on another service

**Comment by wgyt** [comment]
> What? Why would an auth app have in-app announcements?!

exactly, why would we need firebase?
all we need is a banner lol

**Pull request closed without merging**
